=== PabloUrb/dtd/ejercicio05.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT contactos (contacto+)>
<!ELEMENT contacto (nombre, Papellido, Sapellido, edad, direccion, telefono+,es_familiar?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT Papellido (#PCDATA)>
<!ELEMENT Sapellido (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT direccion (Tvia, piso?, puerta?, numero, cpostal, poblacion, pais)>
<!ELEMENT Tvia (#PCDATA)>
<!ELEMENT piso (#PCDATA)>
<!ELEMENT puerta (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT cpostal (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT es_familiar EMPTY>
<!ATTLIST Tvia tipo (calle|plaza|carretera) #REQUIRED>
<!ATTLIST telefono tipo (fijo | movil |casa | trabajo) #REQUIRED>

=== PabloUrb/dtd/ejercicio05.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contactos SYSTEM "ejercicio05.dtd">

<contactos>
    <contacto>
        <nombre>Pablo</nombre>
        <Papellido>urbano</Papellido>
        <Sapellido>murillo</Sapellido>
        <edad>18</edad>
        <direccion>
            <Tvia tipo="calle">calle</Tvia>
            <piso>segundo</piso>
            <puerta>4</puerta>
            <numero>4</numero>
            <cpostal>08031</cpostal>
            <poblacion>barcelona</poblacion>
            <pais>espa√±a</pais>
        </direccion>
        <telefono tipo="fijo">933</telefono>
        <telefono tipo="fijo">933</telefono>
        <es_familiar />
    </contacto>
</contactos>
