=== PabloUrb/dtd/ejercicio04.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pelicula (titulo, director+, año, elemento,genero)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT elemento (protagonista+|tematica+)>
<!ELEMENT protagonista (#PCDATA)>
<!ELEMENT tematica (#PCDATA)>
<!ELEMENT genero EMPTY>
<!ATTLIST genero tipo (drama|comedia|documental|terror|thriller|humor) #REQUIRED>

=== PabloUrb/dtd/ejercicio04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pelicula SYSTEM "ejercicio04.dtd">


<pelicula>
    <titulo>insidious</titulo>
    <director>James Wan</director>
    <año>2011</año>
    <elemento>
         <tematica>miedo</tematica>
           <tematica>miedo</tematica>
    </elemento>
    <genero tipo='drama'/>
</pelicula>
